spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-auth
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: false
    open-in-view: false

jwt:
  secret: 1q2w3e4r!@#$
  accessTokenLiveHours: 1
  refreshTokenLiveHours: 48